# Generated by Django 4.0.3 on 2022-04-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_first_name', models.CharField(max_length=30, null=True)),
                ('cust_last_name', models.CharField(max_length=30, null=True)),
                ('cust_phone_number', models.CharField(max_length=30, null=True)),
                ('cust_email', models.CharField(max_length=30, null=True)),
                ('cust_password', models.CharField(max_length=30, null=True)),
                ('street_address', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('zip', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
