# Generated by Django 4.0.3 on 2022-04-21 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_Address', models.CharField(max_length=255, null=True)),
                ('billing_City', models.CharField(max_length=255, null=True)),
                ('billing_State', models.CharField(max_length=255, null=True)),
                ('billing_Zip', models.CharField(max_length=255, null=True)),
                ('date_Billed', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Billing',
                'ordering': ['date_Billed'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_Name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_First_Name', models.CharField(blank=True, max_length=255)),
                ('customer_Last_Name', models.CharField(blank=True, max_length=255)),
                ('customer_Phone_Number', models.CharField(blank=True, max_length=255)),
                ('customer_Email', models.EmailField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_First_Name', models.CharField(max_length=255, null=True)),
                ('employee_Last_Name', models.CharField(max_length=255, null=True)),
                ('employee_Phone_Number', models.CharField(max_length=255, null=True)),
                ('employee_Email', models.EmailField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expediter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediter_name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_Name', models.CharField(max_length=255, null=True)),
                ('quantity_Per_1000_Units', models.PositiveIntegerField(null=True)),
                ('message_Commands', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Time', models.DateTimeField(null=True)),
                ('end_Time', models.DateTimeField(blank=True, null=True)),
                ('quality_Comments', models.TextField(blank=True, null=True)),
                ('defect_Count', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.employee')),
            ],
            options={
                'ordering': ['start_Time'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_Type', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('order_Status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=255, null=True)),
                ('confirmation_Number', models.CharField(max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.billing')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer')),
            ],
            options={
                'ordering': ['order_Date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image', models.ImageField(blank=True, null=True, upload_to='media/storeapp/product_images')),
                ('product_Version', models.CharField(max_length=255, null=True)),
                ('product_Version_Date', models.DateTimeField(null=True)),
                ('product_Design_File', models.FileField(null=True, upload_to='media/storeapp/product_files')),
                ('product_Comments', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_Address', models.CharField(max_length=255, null=True)),
                ('shipping_City', models.CharField(max_length=255, null=True)),
                ('shipping_State', models.CharField(max_length=255, null=True)),
                ('shipping_Zip', models.CharField(max_length=255, null=True)),
                ('date_Shipped', models.DateTimeField(blank=True, null=True)),
                ('shipment_Cost', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('shipment_Quantity', models.PositiveIntegerField(null=True)),
                ('shipment_Weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer')),
                ('expediter_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.expediter')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.order')),
            ],
            options={
                'verbose_name_plural': 'Shipping',
                'ordering': ['date_Shipped'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=255, null=True)),
                ('product_Description', models.CharField(max_length=255, null=True)),
                ('product_Price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('product_Stock', models.BooleanField(default=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeapp.category')),
                ('job_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.job')),
                ('material_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.material')),
                ('version_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='versionList', to='storeapp.version')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_Number', models.PositiveIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_ID', models.ManyToManyField(related_name='inputs', to='storeapp.inputitem')),
            ],
            options={
                'ordering': ['machine_Number'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='machine_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.machine'),
        ),
        migrations.AddField(
            model_name='inputitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.vendor'),
        ),
        migrations.AddField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
    ]
