# Generated by Django 4.0.3 on 2022-04-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_email',
            new_name='customer_Email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cust_first_name',
            new_name='customer_First_Name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cust_last_name',
            new_name='customer_Last_Name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cust_password',
            new_name='customer_Password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cust_phone_number',
            new_name='customer_Phone_Number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='street_address',
            new_name='street_Address',
        ),
    ]
