# Generated by Django 4.0.3 on 2022-04-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='input_ID',
        ),
        migrations.AddField(
            model_name='machine',
            name='input_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.inputitem'),
        ),
    ]
