# Generated by Django 4.0.3 on 2022-04-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_rename_cust_email_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_First_Name', models.CharField(max_length=30, null=True)),
                ('employee_Last_Name', models.CharField(max_length=30, null=True)),
                ('employee_Phone_Number', models.CharField(max_length=30, null=True)),
                ('employee_Email', models.EmailField(max_length=30, null=True)),
                ('employee_Password', models.CharField(max_length=30, null=True)),
                ('role', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=30, null=True)),
                ('product_Description', models.CharField(max_length=50, null=True)),
                ('product_Price', models.FloatField(null=True)),
                ('product_Stock', models.IntegerField()),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('depth', models.FloatField(null=True)),
                ('product_Image', models.FileField(upload_to='')),
                ('product_Version', models.CharField(max_length=10, null=True)),
                ('product_Version_Date', models.DateTimeField()),
                ('product_Design_File', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_Email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
