# Generated by Django 4.0.3 on 2022-04-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_ID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
