# Generated by Django 4.0.3 on 2022-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_remove_machine_input_id_machine_input_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
