# Generated by Django 4.0.3 on 2022-04-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_remove_order_billing_id_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.order'),
        ),
    ]
