# Generated by Django 4.0.3 on 2022-04-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_product_depth_alter_product_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Comments',
            field=models.TextField(null=True),
        ),
    ]
