# Generated by Django 4.0.3 on 2022-04-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_billing_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
