# Generated by Django 4.0.3 on 2022-04-05 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_order_alter_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
