# Generated by Django 4.0.3 on 2022-04-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_alter_product_version_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version_ID',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product'),
        ),
    ]
