# Generated by Django 4.0.3 on 2022-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_remove_machine_input_id_machine_input_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='input_ID',
            field=models.ManyToManyField(related_name='inputs', to='storeapp.inputitem'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipment_Quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
