# Generated by Django 4.0.3 on 2022-04-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_alter_machine_input_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.vendor'),
        ),
    ]
