# Generated by Django 4.0.3 on 2022-04-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_order_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='machine_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.machine'),
        ),
    ]
