# Generated by Django 4.0.3 on 2022-04-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_alter_job_machine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='machine_ID',
        ),
        migrations.AddField(
            model_name='machine',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.job'),
        ),
    ]
