# Generated by Django 4.0.3 on 2022-04-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_alter_product_version_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediter',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
