# Generated by Django 4.0.3 on 2022-04-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Design_File',
            field=models.FileField(null=True, upload_to='media/storeapp/product_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(null=True, upload_to='media/storeapp/product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Version_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
