# Generated by Django 4.0.3 on 2022-04-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_expediter_slug_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.material'),
        ),
    ]
