# Generated by Django 4.0.3 on 2022-05-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
