# Generated by Django 4.0.3 on 2022-05-03 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_remove_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version_ID',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product'),
        ),
    ]
