# Generated by Django 4.0.3 on 2022-04-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_remove_cartitem_cart_remove_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
