# Generated by Django 4.0.3 on 2022-04-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0017_expediter_vendor_order_order_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediter',
            name='expeditor_Name',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('FedEx', 'FedEx'), ('UPS', 'UPS'), ('OnTrac', 'OnTrac')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
