# Generated by Django 4.0.3 on 2022-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0018_alter_version_product_version_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product_Version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
