# Generated by Django 4.0.3 on 2022-04-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0019_alter_vendor_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediter',
            name='expeditor_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
