# Generated by Django 4.0.3 on 2022-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0019_alter_version_product_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product_Design_File',
            field=models.FileField(blank=True, null=True, upload_to='media/storeapp/product_files'),
        ),
    ]
