# Generated by Django 4.0.3 on 2022-05-03 18:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_alter_version_product_design_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
