# Generated by Django 4.0.3 on 2022-04-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_alter_expediter_expeditor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('Acrylic/Polymethyl Methacrylate (PMMA)', 'Acrylic/Polymethyl Methacrylate (PMMA)'), ('Polycarbonate (PC)', 'Polycarbonate (PC)'), ('Polyethlene (PE)', 'Polyethlene (PE)'), ('Polypropylene (PP)', 'Polypropylene(PP)'), ('Polyethylene Terephthalate (PET)', 'Polyethylene Terephthalate (PET)'), ('Polyvinyl Chloride (PVC)', 'Polyvinyl Chloride (PVC)'), ('Acrylonitrile-Butadiene-Stryrene (ABS)', 'Acrylonitrile-Butadiene-Stryrene (ABS)')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='material_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.material'),
        ),
    ]
