# Generated by Django 4.0.3 on 2022-05-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='job_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.job'),
        ),
    ]
