# Generated by Django 4.0.3 on 2022-04-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_material_product_material_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_type',
            new_name='material_Type',
        ),
    ]
