# Generated by Django 4.0.3 on 2022-05-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0022_alter_product_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
    ]
