# Generated by Django 4.0.3 on 2022-04-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0022_rename_material_type_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Design_File',
            field=models.FileField(blank=True, null=True, upload_to='media/storeapp/product_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/storeapp/product_images'),
        ),
    ]
