# Generated by Django 4.0.3 on 2022-04-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0023_alter_product_product_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_Comments', models.TextField(blank=True, null=True)),
                ('defect_Count', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='date_Created',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_No', models.IntegerField(null=True)),
                ('start_Time', models.DateTimeField(null=True)),
                ('end_Time', models.DateTimeField(auto_now_add=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('per_1000_Units', models.PositiveIntegerField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.employee')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product')),
                ('quality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.quality')),
            ],
        ),
    ]
