# Generated by Django 4.0.3 on 2022-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0024_alter_inputitem_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=255, null=True),
        ),
    ]
