# Generated by Django 4.0.3 on 2022-04-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0024_quality_rename_date_created_order_date_created_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image', models.ImageField(blank=True, null=True, upload_to='media/storeapp/product_images')),
                ('product_Version', models.CharField(max_length=10, null=True)),
                ('product_Version_Date', models.DateTimeField(null=True)),
                ('product_Design_File', models.FileField(blank=True, null=True, upload_to='media/storeapp/product_files')),
                ('product_Comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Design_File',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Version_Date',
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.version'),
        ),
    ]
