# Generated by Django 4.0.3 on 2022-05-09 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0025_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='machine_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.machine'),
        ),
    ]
