# Generated by Django 4.0.3 on 2022-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0025_version_remove_product_product_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.ManyToManyField(to='storeapp.version'),
        ),
    ]
