# Generated by Django 4.0.3 on 2022-04-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0026_remove_product_version_product_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_Created',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
