# Generated by Django 4.0.3 on 2022-04-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0027_rename_date_created_order_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_Name', models.CharField(max_length=30, null=True)),
                ('quantity_Per_1000_Units', models.PositiveIntegerField(null=True)),
                ('message_Commands', models.TextField(blank=True, null=True)),
                ('vendor', models.ManyToManyField(to='storeapp.vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='per_1000_Units',
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.inputitems')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='machine_No',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.inputitems'),
        ),
    ]
