# Generated by Django 4.0.3 on 2022-04-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0028_inputitems_remove_job_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.CreateModel(
            name='InputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_Name', models.CharField(max_length=30, null=True)),
                ('quantity_Per_1000_Units', models.PositiveIntegerField(null=True)),
                ('message_Commands', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='machine_No',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.inputitem'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.inputitem'),
        ),
        migrations.DeleteModel(
            name='InputItems',
        ),
    ]
