# Generated by Django 4.0.3 on 2022-05-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0028_alter_billing_customer_alter_billing_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='machine',
        ),
        migrations.AddField(
            model_name='job',
            name='machine_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.machine'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.order'),
        ),
        migrations.AlterField(
            model_name='inputitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.vendor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.employee'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='job_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.job'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versionList', to='storeapp.version'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='expediter_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.expediter'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.order'),
        ),
        migrations.AlterField(
            model_name='version',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
    ]
