# Generated by Django 4.0.3 on 2022-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0029_remove_order_vendor_inputitem_alter_job_machine_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_No',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
