# Generated by Django 4.0.3 on 2022-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0032_remove_machine_input_machine_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='input',
        ),
        migrations.AddField(
            model_name='machine',
            name='input',
            field=models.ManyToManyField(to='storeapp.inputitem'),
        ),
    ]
