# Generated by Django 4.0.3 on 2022-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0033_remove_machine_input_machine_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='storeapp.product'),
        ),
    ]
