# Generated by Django 4.0.3 on 2022-04-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0035_remove_order_product_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_Address', models.CharField(max_length=30, null=True)),
                ('billing_City', models.CharField(max_length=30, null=True)),
                ('billing_State', models.CharField(max_length=30, null=True)),
                ('billing_Zip', models.CharField(max_length=30, null=True)),
                ('date_Billed', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='machine_No',
            new_name='machine_ID',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='quality',
            new_name='quality_ID',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machine_No',
            new_name='machine_Number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_Type',
            new_name='material_ID',
        ),
        migrations.RemoveField(
            model_name='inputitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='job',
            name='product',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='input',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expediter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expediter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='input_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_Number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_Status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='job_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.job'),
        ),
        migrations.AddField(
            model_name='product',
            name='version_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.version'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_Address', models.CharField(max_length=30, null=True)),
                ('shipping_City', models.CharField(max_length=30, null=True)),
                ('shipping_State', models.CharField(max_length=30, null=True)),
                ('shipping_Zip', models.CharField(max_length=30, null=True)),
                ('date_Shipped', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipment_Cost', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('shipment_Quantity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('shipment_Weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('expediter_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.expediter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.billing'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_quantity_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.orderquantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.shipping'),
        ),
    ]
