# Generated by Django 4.0.3 on 2022-04-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0037_categories_product_category_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orderquantity',
            options={'verbose_name_plural': 'Order Quantities'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name_plural': 'Quality Information'},
        ),
    ]
