# Generated by Django 4.0.3 on 2022-04-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0038_rename_categories_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name_plural': 'Billing'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name_plural': 'Shipping'},
        ),
        migrations.AddField(
            model_name='billing',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='machine_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.machine'),
        ),
    ]
