# Generated by Django 4.0.3 on 2022-04-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0039_alter_billing_options_alter_shipping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderquantity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Stock',
            field=models.BooleanField(default=True),
        ),
    ]
