# Generated by Django 4.0.3 on 2022-04-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0041_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity_ID',
        ),
        migrations.AddField(
            model_name='order',
            name='order_quantity_ID',
            field=models.ManyToManyField(to='storeapp.orderquantity'),
        ),
    ]
