# Generated by Django 4.0.3 on 2022-04-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0042_remove_order_order_quantity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
