# Generated by Django 4.0.3 on 2022-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0045_remove_order_product_orderquantity_date_created_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
