# Generated by Django 4.0.3 on 2022-04-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0046_cart_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity_ID',
        ),
        migrations.AddField(
            model_name='order',
            name='order_quantity_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.orderquantity'),
        ),
    ]
