# Generated by Django 4.0.3 on 2022-04-11 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0050_rename_orderquantity_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name_plural': 'Quality Information'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='job',
            name='quality_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.quality'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=20, null=True),
        ),
    ]
