# Generated by Django 4.0.3 on 2022-04-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0051_alter_quality_options_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='quality_ID',
        ),
        migrations.AddField(
            model_name='job',
            name='defect_Count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='quality_Comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
    ]
