# Generated by Django 4.0.3 on 2022-04-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0052_remove_job_quality_id_job_defect_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='input_ID',
        ),
        migrations.AddField(
            model_name='machine',
            name='input_ID',
            field=models.ManyToManyField(to='storeapp.inputitem'),
        ),
    ]
