# Generated by Django 4.0.3 on 2022-04-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0053_remove_machine_input_id_machine_input_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
