# Generated by Django 4.0.3 on 2022-04-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0054_alter_job_end_time_alter_job_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
