# Generated by Django 4.0.3 on 2022-04-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0055_alter_job_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='defect_Count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='product_Design_File',
            field=models.FileField(null=True, upload_to='media/storeapp/product_files'),
        ),
    ]
