# Generated by Django 4.0.3 on 2022-04-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0056_billing_customer_alter_job_defect_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
    ]
