# Generated by Django 4.0.3 on 2022-04-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0057_shipping_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['date_Billed'], 'verbose_name_plural': 'Billing'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['customer']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['start_Time']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['machine_Number']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_Date']},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['date_Shipped'], 'verbose_name_plural': 'Shipping'},
        ),
        migrations.AlterField(
            model_name='material',
            name='material_Type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_Shipped',
            field=models.DateTimeField(null=True),
        ),
    ]
