# Generated by Django 4.0.3 on 2022-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0058_alter_billing_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
