# Generated by Django 4.0.3 on 2022-04-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0059_material_date_created_material_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='inputitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inputitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
