# Generated by Django 4.0.3 on 2022-04-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0060_rename_date_create_cart_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date_Billed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.customer'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.cart'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_Shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
