# Generated by Django 4.0.3 on 2022-04-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0061_alter_billing_date_billed_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date_Billed',
            field=models.DateTimeField(null=True),
        ),
    ]
